<?xml version="1.0"?>
<!--
   This file is used in the example of the xmlnumber parser object
   class, described in the "Using the XML Parser Object Class"
   chapter of _Building IDL Applications_.
-->

<!DOCTYPE array [
   <!ELEMENT array (number+)>
   <!ELEMENT number (#PCDATA)>
]>

<array>  
  	<number>0</number>  
 	<number>1</number>
 	<number>2</number>
 	<number>3</number>
 	<number>4</number>
 	<number>5</number>
 	<number>6</number>
 	<number>7</number>
 	<number>8</number>
 	<number>9</number>
 	<number>10</number>
 	<number>11</number>
 	<number>12</number>
 	<number>13</number>
 	<number>14</number>
 	<number>15</number>
 	<number>16</number>
 	<number>17</number>
 	<number>18</number>
 	<number>19</number>
</array>
